### ISSUE TITLE
video reid 讨论

### ISSUE THREAD

**Issue by zhangzhengjie626** [DeepAlchemist/video-person-reID#1]
大佬，我也在研究video person reid，能给个联系方式讨论一下吗？或者，加一下我的联系方式：qq 1051557122 十分感谢。

**Comment by zhangzhengjie626** [comment]
我试了下代码，按默认的配置跑不起来，请问base-model 是resnet50  还是resnet101呢？ 谢谢。

**Comment by deepalchemist** [comment]
Thanks for your interest. The base model is resnet50, and I have updated the config, you can have a try again.

**Comment by deepalchemist** [comment]
> 大佬，我也在研究video person reid，能给个联系方式讨论一下吗？或者，加一下我的联系方式：qq 1051557122 十分感谢。

OK.

**Comment by zhangzhengjie626** [comment]
大佬，我没收到好友请求。。我想问一下，你的baseline在MARS上 R1和mAP是多少？另外如果Non-Local 和 cmm全叠上去，性能能提升多少？如果只加cmm模块，会提升到多少？十分感谢。

**Comment by deepalchemist** [comment]
I will report the performance and release the trained model, as soon as possible.
